---
title: "A Tutorial on Time-Dependent Cohort State-Transition Models in R using a Cost-Effectiveness Analysis Example"
subtitle: "Appendix"
author: 
  - Fernando Alarid-Escudero, PhD^[Division of Public Administration, Center for Research and Teaching in Economics (CIDE), Aguascalientes, AGS, Mexico]
  - Eline Krijkamp, MSc^[Department of Epidemiology and Department of Radiology, Erasmus University Medical Center, Rotterdam, The Netherlands]
  - Eva A. Enns, PhD^[Division of Health Policy and Management, University of Minnesota School of Public Health, Minneapolis, MN, USA]
  - Alan Yang, MSc^[The Hospital for Sick Children, Toronto]
  - Myriam G.M. Hunink, PhD$^\dagger$^[Center for Health Decision Sciences, Harvard T.H. Chan School of Public Health, Boston, USA]
  - Petros Pechlivanoglou, PhD^[The Hospital for Sick Children, Toronto and University of Toronto, Toronto, Ontario, Canada]
  - Hawre Jalal, MD, PhD^[University of Pittsburgh, Pittsburgh, PA, USA]
date: '`r Sys.Date()`'
output: 
  pdf_document:
    keep_tex: yes
classoption: landscape
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

## Cohort tutorial model components
This table contains an overview of the key model components used in the code for the Sick-Sicker example from the [DARTH](http://darthworkgroup.com/) manuscript: [“A Tutorial on Time-Dependent Cohort State-Transition Models in R”](https://arxiv.org/abs/2108.13552). The first column gives the mathematical notation for some of the model components that are used in the equations in the manuscript. The second column gives a description of the model component with the R name in the third column. The forth gives the data structure, e.g. scalar, list, vector, matrix etc, with the according dimensions of this data structure in the fifth column. The final column indicated the type of data that is stored in the data structure, e.g. numeric (5.2,6.3,7.4), category (A,B,C), integer (5,6,7), logical (TRUE, FALSE).

| Element | Description                           | R name        | Data structure | Dimensions        | Data type   |
|--------|---------------------------------------|----------------|----------------|-------------------|-------------|
| $n_t$        | Time horizon                     | `n_cycles`   | scalar          |                   | numeric     |
|              | Cycle length                     | `cycle_length`| scalar         |                   | numeric     |
| $v_s$        | Names of the health states       | `v_names_states`| vector       | `n_states` x 1    | character   |
| $n_s$        | Number of health states          | `n_states`   | scalar          |                   | numeric     |
| $n_{S_{tunnels}}$   | Number of health states with tunnels    | `n_states_tunnels`    scalar  |      | numeric     |
| $v_{str}$    | Names of the strategies          | `v_names_str`| scalar          |                   | character   |
| $n_{str}$    | Number of strategies             | `n_str`      | scalar          |                   | character   |
| \(d_c\)      | Discount rate for costs          | `d_c`        | scalar          |                   | numeric     |
| \(d_e\)      | Discount rate for effects        | `d_e`        | scalar          |                   | numeric     |
| \(\mathbf{d_c}\) | Discount weights vector for costs  | `v_dwc`      | vector    | (`n_t` x 1 ) + 1  | numeric     | 
| \(\mathbf{d_e}\) | Discount weights vector for effects| `v_dwe`      | vector    | (`n_t` x 1 ) + 1  | numeric     | 
|              | Sequence of cycle numbers        | `v_cycles`   | vector          | (`n_t` x 1 ) + 1  | numeric     | 
|\(\mathbf{wcc}\) | Within-cycle correction weights | `v_wcc`    | vector          | (`n_t` x 1 ) + 1  | numeric     |
| $age_{_0}$   | Age at baseline                  | `n_age_init` | scalar          |                   | numeric     |
| $age$        | Maximum age of follow up         | `n_age_max`  | scalar          |                   | numeric     |
| \(M\)        | Cohort trace matrix              | `m_M`       | matrix | (`n_t` + 1) x `n_states`    | numeric     |
| \(M_{tunnels}\) | Aggregated Cohort trace for state-dependency  | `m_M_tunnels`  | matrix   | (`n_t` + 1) x `n_states`    | numeric     |
|              | List of the cohort trace matrix for all strategies | `l_m_M`  | list   |              | numeric     |
| \(m_0\)      | Initial state vector             | `v_m_init`   | vector          | 1 x `n_states`    | numeric     |
| \(m_t\)      | State vector in cycle $t$        | `v_mt`       | vector          | 1 x `n_states`    | numeric     |
|              |                                  |              |                 |                   |             |
|              |  **Life table input**    |              |                 |                           |             |  
|              | State vector in cycle $t$        | `lt_usa_2005`| list            |                   | numeric     |
|              | Vector of age-specific mortality rates | `v_r_mort_by_age` | vector        |          | numeric     |
|              |                                  |              |                 |                        |             |
|              |  **Transition probabilities and rates**    |              |                 |                   |             |  
| $r_{[H,S1]}$  | Constant rate of becoming Sick when Healthy  | `r`_HS1`      | scalar          |    | numeric     |
| $r_{[S1,H]}$  | Constant rate of becoming Healthy when Sick  | `r`_S1H`      | scalar          |    | numeric     |
| $p_{[H,S1]}$  | From Healthy to Sick conditional on surviving  | `p_HS1`      | scalar          |    | numeric     |
| $p_{[S1,H]}$  | From Sick to Healthy conditional on surviving  | `p_S1H`      | scalar          |    | numeric     |
| $p_{[S1,S2]}$ | From Sick to Sicker conditional on surviving   | `p_S1S2`     | scalar          |    | numeric     |
| $r_{[H,D]}$   | Constant rate of dying when Healthy (all-cause mortality rate)| `r_HD`| scalar  |    | numeric     |
| $r_{[S1,S2]}$   | Constant rate of becoming Sicker when Sick   | `r_S1S2`       | scalar          |                   | numeric     |
| $r_{[S1,S2]_{trtB}}$   | Constant rate of becoming Sicker when Sick for treatment B| `r_S1S2_trtB`       | scalar          |                   | numeric     |
| $hr_{[S1,H]}$ | Hazard ratio of death in Sick vs Healthy       | `hr_S1`       | scalar          |                   | numeric     |
| $hr_{[S2,H]}$ | Hazard ratio of death in Sicker vs Healthy     | `hr_S2`       | scalar          |                   | numeric     |
| $hr_{[S1,S2]_{trtB}}$ | Hazard ratio of becoming Sicker when Sick under treatment B    | `hr_S1S2_trtB`| scalar   |  | numeric     |
| $p_{[S1,S2]_{trtB}}$ | Probability to become Sicker when Sick under treatment B conditional on surviving | `p_S1S2_trtB`| scalar   |  | numeric     |
|              |                                  |              |                 |                        |             |
|              |  **Weibull parameters for transition probability of becoming Sicker when Sick conditional on surviving** |              |                 |                   |             |  
| $\lambda$    | scale of the Weibull hazard function  | `p_S1S2_scale`      | scalar          |                   | numeric     |
| $\gamma$     | shape  of the Weibull hazard function | `p_S1S2_shape`      | scalar          |                   | numeric     |
|              |                                  |              |                 |                        |             |
|               |  **Simulation-time dependent mortality**                      |              |                 |                   |             |
| $r_{[H,D,t]}$ | Age-specific background mortality rates          | `v_r_HDage`   | vector   | `n_t` x 1   | numeric     |
| $r_{[S1,D,t]}$| Age-specific mortality rates in the Sick state   | `v_r_S1Dage`  | vector   | `n_t` x 1   | numeric     |
| $r_{[S2,D,t]}$| Age-specific mortality rates in the Sicker state | `v_r_S2Dage`  | vector   | `n_t` x 1   | numeric     |
| $p_{[H,D,t]}$ | Age-specific mortality risk in the Healthy state | `v_p_HDage`   | vector   | `n_t` x 1   | numeric     |
| $p_{[S1,D,t]}$| Age-specific mortality rates in the Sick state   | `v_p_S1Dage`  | vector   | `n_t` x 1   | numeric     |
| $p_{[S2,D,t]}$| Age-specific mortality rates in the Sicker state | `v_p_S2Dage`  | vector   | `n_t` x 1   | numeric     |
| $p_{[S1,S2, t]}$ | Time-dependent transition probabilities from sick to sicker  |`v_p_S1S2_tunnels` | vector | `n_t` x 1 | numeric |
| $\mu_{[S1_{\tau},S2, \tau]}$ | State-residence time-dependent transition rate of becoming Sicker when Sick |`v_r_S1S2_tunnels` | vector | `n_t` x 1 | numeric |
|               |                                |               |                 |                   |           |
|        | **Annual costs**                      |               |                 |                   |           |
|              | Healthy individuals             | `c_H`         | scalar          |                   | numeric   |
|              | Sick individuals in Sick        | `c_S1`        | scalar          |                   | numeric   |
|              | Sick individuals in Sicker      | `c_S2`        | scalar          |                   | numeric   |
|              | Dead individuals                | `c_D`         | scalar          |                   | numeric   | 
|              | Additional costs treatment A    | `c_trtA`      | scalar          |                   | numeric   | 
|              | Additional costs treatment B    | `c_trtB`      | scalar          |                   | numeric   | 
|              | Vector of state costs for a strategy       | `v_c_str`    |  vector        | 1 x `n_states`    | numeric   |
|              | List that stores the vectors of state costs for each strategy     | `l_c`    |  List        |     | numeric   |
|              |                                 |               |                 |                   |           |
|              | **Utility weights**             |               |                 |                   |           |
|              |  Healthy individuals            | `u_H`         | scalar          |                   | numeric   |
|              |  Sick individuals in Sick       | `u_S1`        | scalar          |                   | numeric   |
|              |  Sick individuals in Sicker     | `u_S2`        | scalar          |                   | numeric   |
|              |  Dead individuals               | `u_D`         | scalar          |                   | numeric   | 
|              |  Treated with treatment A       | `u_trtA`      | scalar          |                   | numeric   | 
|              |  Vector of state utilities for a strategy        | `v_u_str`    |  vector        | 1 x `n_states`    | numeric   |
|              |  Vector of S1 utilities when including state-residency for a strategy SoC for         | `v_u_S1_SoC`    |  vector        | 1 x `n_tunnel_size`    | numeric   |
|              |  List that stores the vectors of state utilities for each strategy     | `l_u`    |  List        |     | numeric   |
|              |                                 |               |                 |                   |           |
|              | **Transition weights**          |               |                 |                   |           |
|              | Utility decrement of healthy individuals when transitioning to S1 | `du_HS1`| scalar  | | numeric |
|              | Cost of healthy individuals when transitioning to S1  |    `ic_HS1`          | scalar  | | numeric |
|              | Cost of dying                   |                          `ic_D`           | scalar  | | numeric |
|              |                                 |               |                 |                   |           |
|              | **Tunnel state structures**                       |               |                 |                   |           |
|              | number of tunnel states         | `n_tunnel_size` | scalar        |                   |  numeric  |
|              | vector with cycles for  tunnels states     | `v_cycles_tunnel` | vector        |     1 x `n_tunnel_size`       |  numeric  |
|              | tunnel names of the Sick state  | `v_Sick_tunnel` | vector        | 1 x `n_states`    | numeric   |
|              | state names including tunnel states | `v_names_states_tunnels` | vector       | 1 x `n_states_tunnels`    | character |
|              | number of states including tunnel states | `n_states_tunnels`     | scalar   |        | numeric   |
|              | Initial state vector for the model with tunnels  |  `v_m_init_tunnels` | vector  | 1 x `n_states_tunnels`   | numeric   |
|              |                                  |              |                 |                        |             |
| \(\mathbf{P}\)| Time-dependent transition probability array  | `a_P`  | array  | `n_states` x `n_states` x `n_t` | numeric |
| \(\mathbf{P}_{tunnels}\)| Transition probability array for the model with tunnels  | `a_P_tunnels`  | array  |  `n_states_tunnels` x `n_states_tunnels` x `n_t` | numeric |
| \(\mathbf{A}\)| Transition dynamics array                    |`a_A`   | array  |`n_states` x `n_states` x (`n_t` + 1)  | numeric |
|              | List of the transition dynamics arrays for all strategies | `l_m_A`  | list   |                   | numeric     |
| \(\mathbf{R_u}\) | Transition rewards for effects            |`a_R_u` | array  |`n_states` x `n_states` x (`n_t` + 1)   | numeric   |
| \(\mathbf{R_c}\) | Transition rewards for costs              |`a_R_c` | array  |`n_states` x `n_states` x (`n_t` + 1)  | numeric   |
| \(\mathbf{Y_u}\) | Expected effects per states per cycle     |`a_Y_u` | array  |`n_states` x `n_states` x (`n_t` + 1)   | numeric   |
| \(\mathbf{Y_c}\) | Expected costs per state per cycle        |`a_Y_c` | array  |`n_states` x `n_states` x (`n_t` + 1)  | numeric   |
|              |                                             |           |        |                    |             |      |  
|              | Expected QALYs per cycle under a strategy      | `v_qaly_str`     | vector        | 1 x (`n_t` + 1)    | numeric   |
|              | Expected costs per cycle under a strategy      | `v_cost_str`     | vector        | 1 x (`n_t` + 1)    | numeric   |
|              | Vector of expected discounted QALYs for each strategy  | `v_tot_qaly`  |  vector  |    1 x `n_states`      | numeric   |
|              | Vector of expected discounted costs for each strategy  | `v_tot_cost`|  vector    |  1 x `n_states`            | numeric   |
|              | Summary matrix with costs and QALYS per strategy| `m_outcomes`    | table          |  `n_states`  x 2   |           |
|              | Summary of the model outcomes                  | `df_cea`         | data frame    |                    |           |
|              | Summary of the model outcomes                  | `table_cea`     | table         |                    |           |
|              | Input parameters values of the model for the cost-effectiveness analysis   | `df_psa` | data frame  | |          |
|              |  *NOTE: these structures can have `_strX` to indicate the strategy of interest          |            |          |            | 
|              |                                             |           |        |                    |             |      |  
|              |  **Probabilistic analysis  structures**         |               |                 |                   |             |
|              | Number of PSA iterations         | `n_sim`      | scalar          |                   | numeric     |
|              | List that stores all the values of the input parameters     | `l_params_all`    |  list        |     | numeric   |
|              | Data frame with the parameter values for each PSA iteration    | `df_psa_input`    |  data frame        |     | numeric   |
|              | Vector with the names of all the input parameters    | `v_names_params`    |  vector      |     | character   |
|              | List with the model outcomes of the PSA for all strategies    | `l_psa`    |  list        |     | numeric   |
|              | Vector with a sequence of relevant willingness-to-pay values    | `v_wtp`    |  vector      |     | numeric   |
|              | Data frame to store expected costs and effects for each strategy from the PSA    | `df_out_ce_psa`  | data frame          |     |    numeric       |
|              | Data frame to store incremental cost-effectiveness ratios (ICERs) from the PSA    | `df_cea_psa`  | data frame          |     |    numeric       |
|              |     For more details about the PSA structures read `dampack`'s vignettes  |               |                 |                   |           |
